name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git clone git@github.com:WelpNathan/Highfield.git
          dotnet publish -c release -o publish -r linux-x64
          cd Highfield/ExamInvigilatorProject/publish
          chmod 777 ./ExamInvigilatorProject
          ./ExamInvigilatorProject.dll
