name: AWS Continuous Delivery
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo systemctl stop highfield.service
          cd ~
          rm -rf Highfield
          git clone git@github.com:WelpNathan/Highfield.git
          cd Highfield/ExamInvigilatorProject
          dotnet publish -o publish -r linux-x64
          sudo systemctl restart highfield.service
